CREATE DATABASE IF NOT EXISTS CollegeDB;

USE CollegeDB;

CREATE TABLE IF NOT EXISTS Students (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(100),
    RollNo VARCHAR(20),
    Department VARCHAR(50)
);

USE CollegeDB;

ALTER TABLE Students
ADD COLUMN TotalFees DECIMAL(10,2),
ADD COLUMN FeesPaid DECIMAL(10,2),
ADD COLUMN RemainingFees DECIMAL(10,2);
